export const FETCH_USERS = 'USER/FETCH_USERS';
export const REQUEST_USERS = 'USER/REQUEST_USERS';
export const SELECT_USER = 'USER/SELECT_USER';
export const UNSELECT_USER = 'USER/UNSELECT_USER';
export const FILTER_FETCHED_USERS = 'USER/FILTER_FETCHED_USERS';
export const FILTER_SELECTED_USERS = 'USER/FILTER_SELECTED_USERS';
export const SHOW_LOADER = 'APP/SHOW_LOADER';
export const HIDE_LOADER = 'APP/HIDE_LOADER';
